# Generated by Django 5.0.3 on 2024-03-22 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0004_alter_business_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='business',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='step.business'),
        ),
    ]
