# Generated by Django 5.0.3 on 2024-03-23 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0005_alter_supplier_business'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='credit',
            new_name='opening_credit',
        ),
    ]
