# Generated by Django 5.0.3 on 2024-03-23 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0006_rename_credit_customer_opening_credit'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
