# Generated by Django 5.0.3 on 2024-03-23 07:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0007_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('Buying_price', models.IntegerField()),
                ('selling_price', models.IntegerField()),
                ('alert_quantity', models.IntegerField(default=3)),
                ('stock', models.IntegerField()),
                ('product_picture', models.ImageField(upload_to='')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.supplier')),
            ],
        ),
    ]
