# Generated by Django 5.0.3 on 2024-03-23 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0008_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(upload_to='images'),
        ),
    ]
