# Generated by Django 5.0.3 on 2024-03-29 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0011_status_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
