# Generated by Django 5.0.3 on 2024-03-29 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0012_alter_products_product_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
