# Generated by Django 3.2.19 on 2024-06-08 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0015_mode_of_payment_alter_purchase_date_sells'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='expenses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_to_bepaid', models.IntegerField()),
                ('amount_paid', models.IntegerField()),
                ('expense_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.expense_category')),
            ],
        ),
    ]
