# Generated by Django 3.2.19 on 2024-06-11 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0019_notifications_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_picture',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
