# Generated by Django 3.2.19 on 2024-06-12 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0020_alter_products_product_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='sells',
            old_name='total',
            new_name='Amount_due',
        ),
        migrations.RemoveField(
            model_name='sells',
            name='product_sold',
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount_paid', models.IntegerField()),
                ('date_paid', models.DateTimeField(auto_now_add=True)),
                ('mode_of_payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.mode_of_payment')),
                ('sellid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='step.sells')),
            ],
        ),
        migrations.AddField(
            model_name='sells',
            name='Payment_status',
            field=models.ForeignKey(default=10, on_delete=django.db.models.deletion.CASCADE, to='step.payment_status'),
            preserve_default=False,
        ),
    ]
