# Generated by Django 3.2.19 on 2024-06-12 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0021_auto_20240612_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='Product_sold',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='step.products'),
            preserve_default=False,
        ),
    ]
