# Generated by Django 3.2.19 on 2024-06-14 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step', '0022_sells_product_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sells',
            name='Amount_paid',
            field=models.IntegerField(default=0),
        ),
    ]
